version: '3.7'

services:
  pgsql:
    container_name: pgsql
    image: postgres:latest
    environment:
      POSTGRES_DB: software-architecture-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sgbd/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rhribeiro_25@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "16543:80"
    volumes:
      - ./sgbd/pgadmin:/var/lib/pgadmin
    depends_on:
      - pgsql

networks:
  default:
    name: software-architecture-net
    driver: bridge